### ISSUE TITLE
Bulk bouncing fails ?

### ISSUE THREAD

**Issue by MikeGriffinReborn** [hosuaby/Leaflet.SmoothMarkerBouncing#55]
If I do this on a context menu click it works perfectly ...

```javascript
function indicateOnline(e) {
	let marker = e.relatedTarget.repeater.marker;
	marker.toggleBouncing();
}
```

Where as this fails ??

```javascript
function refreshOnlineRepeaters() {
	let arrayLength = g_MasterRepeaters.repeaters.length;

	for (let i = 0; i < arrayLength; i++) {
		let repeater = g_FilteredRepeaters.repeaters[i];

		if (i % 20 === 0) {
			repeater.marker.toggleBouncing();
		}
	}
}
```

The error is ...

```
Uncaught TypeError: Cannot read properties of undefined (reading 'classList')
    at Object.z [as removeClass] (leaflet.js:5:24238)
    at bouncing.min.js:1:7574
    at Array.forEach (<anonymous>)
    at B (bouncing.min.js:1:7534)
    at M.value (bouncing.min.js:1:11705)
    at e.bounce (bouncing.min.js:1:4226)
    at e.toggleBouncing (bouncing.min.js:1:4610)
    at e.refreshOnlineRepeaters (menuhandlers.js:154:20)
    at HTMLAnchorElement.<anonymous> (leaflet.contextmenu.js:338:26)
    at HTMLAnchorElement.o (leaflet.js:5:27827)
```

**Comment by MikeGriffinReborn** [comment]
It seems as though you can only get it to work if you grab the marker from the event.relatedTarget, otherwise it's not setup right?

**Comment by hosuaby** [comment]
Hello @MikeGriffinReborn 

Bulk bouncing is working well as long as I know. It's difficult to get the cause from your code snippet cause I don't know the content of `g_MasterRepeaters.repeaters`. But from this exeption, I can presume that some of the markers that make part of this list were not added on the map priot to calling `repeater.marker.toggleBouncing();`.

**Comment by sbagshaw-shore** [comment]
I had this same error and I had to add a line `myMarker.addTo(this.mapObject);` with `mapObject` being an object of class `L.Map`.

The same code used to work in SmoothMarkerBouncing code before version 3.

**Comment by hosuaby** [comment]
@sbagshaw-shore This actually makes sense. You have to add a marker to the map before you can make it bounce. The fact that it was working prior to version 3 is just a coincidence. Could you provide a snippet explaining why it should be otherwise?

**Comment by sbagshaw-shore** [comment]
Hi @hosuaby - not sure. I guess the thing that is odd is that I loop through all the markers on the map to set the icon, colours, z-index etc, but I only need to do this explicit `addTo()` call for the ones that are going to bounce. So I feel like the markers are already there.

**Comment by hosuaby** [comment]
@MikeGriffinReborn @sbagshaw-shore 

I found the reason of the bug. Fixed in `3.1.1`. But this is unspecified behavour. It is always better to add markers to the map before making them bouncing.
